# This workflow extracts translation source files from code and adds the extracted
# translation source files to the openedx-translations repository via an auto-merged pull
# request.

name: Extract Translation Source Files

on:
  workflow_dispatch:    # by request
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  setup-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.dynamic_branch.outputs.branch }}
    steps:
    # sets the job output that creates a unique branch name
    - name: dynamically set branch job output variable
      id: dynamic_branch
      run: echo "::set-output name=branch::automated/extract-translation-source-files-$(date +'%Y%m%dT%H%M%S')"

    # clones the openedx-translations repo so a branch can be added in the next step
    - name: echo branch name
      id: date
      run: echo $BRANCH
    - name: clone openedx/openedx-translations
      uses: actions/checkout@v3
    
    # creates the branch where all the translations will be added to
    - name: make and push a new branch
      run: |
        git checkout -b ${{ steps.dynamic_branch.outputs.branch }}
        git push --set-upstream origin ${{ steps.dynamic_branch.outputs.branch }}

  python-translations:
    strategy:
      matrix:
        repo: [credentials]
    runs-on: ubuntu-latest
    needs: [setup-branch]

    steps:
      # Clones the openedx-translations repo
      - name: clone openedx/openedx-translations
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.setup-branch.outputs.branch }}
      
      # Installs gettext, a dependency for extracting translation source files in django
      - name: install gettext
        run: sudo apt install -y gettext

      # Clones the  repository
      - name: clone Carlos-Muniz/${{ matrix.repo }}
        uses: actions/checkout@v3
        with:
          repository: openedx/${{ matrix.repo }}
          path: ${{ matrix.repo }}

      # Sets up Python
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      # Installs Python requirements from translations.txt
      - name: install requirements
        run: |
          cd ${{ matrix.repo }}
          pip install -r requirements/translations.txt

      # Extracts the translation source files
      - name: extract translation source files
        run: |
          cd ${{ matrix.repo }}
          make extract_translations
      
      # git adds only the translation source files, found in conf/locale/en
      - name: git add the translation source files
        id: add-sources
        run: |
          # set identity
          git config --global user.email "translations-bot@openedx.org"
          git config --global user.name "edx-transifex-bot"
          # finds the directory containing the english locale usually located in
          # */*/conf/locale/en
          EN_DIR=$(find . -type d -regex ".+conf\/locale\/en$")
          # remove ${{ matrix.repo }}/.git so we don't commit a submodule
          rm -rf ${{ matrix.repo }}/.git
          # finds the django.po and djangojs.po files generated by make
          # extract_translations into EN_DIR and adds them
          DJANGO_PATH=$(find $EN_DIR -name 'django.po')
          DJANGOJS_PATH=$(find $EN_DIR -name 'djangojs.po')
          git add $DJANGO_PATH $DJANGOJS_PATH -v
          # Check the git statuses of the translation source files
          echo "::set-output name=GIT_STATUS::$(git status $DJANGO_PATH $DJANGOJS_PATH -s)"
  
          
      # Attempts to commit the translation source files if there is a difference
      - name: git commit the translation source files
        if: "${{ steps.add-sources.outputs.GIT_STATUS != '' }}"
        run: |
          # commit the changes
          git commit -m "chore: add extracted translation source files from ${{ matrix.repo }}"
          # push changes to branch
          git push
          
  merge-translations:
    runs-on: ubuntu-latest
    needs: [setup-branch, python-translations]

    steps:
      # Clones the openedx-translations repo on the automated/extract-translation-source-files-# branch
      - name: clone openedx/openedx-translations
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.setup-branch.outputs.branch }}
      
      # Create a pull request
      - name: create pull request
        id: createPR
        env:
          # This token requires Write access to the openedx-translations repo
          GITHUB_TOKEN: ${{ secrets.EDX_TRANSIFEX_BOT_GITHUB_TOKEN }}
        run: |
          echo "::set-output name=PR_URL::$(gh pr create --title 'chore: add updated translation source files' --body 'This PR is auto-generated by [extract-translation-source-files](https://github.com/openedx/openedx-translations/blob/master/.github/workflows/extract-translation-source-files.yml).')"
      
      # Merges the pull request
      - name: merge pull request
        env:
          # This token requires Write access to the openedx-translations repo
          GITHUB_TOKEN: ${{ secrets.EDX_TRANSIFEX_BOT_GITHUB_TOKEN }}
        run: gh pr merge ${{ steps.createPR.outputs.PR_URL }} --merge --delete-branch
        
#       # Delete the branch
#       - name: delete branch
#         run: git push origin -d ${{ needs.setup-branch.outputs.branch }}
        
